apiVersion: v2
name: ciso-assistant
description: A Helm chart for CISO Assistant k8s's deployment
type: application
version: 0.7.6
appVersion: "v3.10.2"
home: https://github.com/tashiscool/ciso-assistant-community
sources:
  - https://github.com/tashiscool/ciso-assistant-community
dependencies:
  - name: postgresql
    version: "16.6.3"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
